// <auto-generated />
namespace KotareParable.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class init_responses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_responses));
        
        string IMigrationMetadata.Id
        {
            get { return "201505010335293_init_responses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
